= DMIT2015 Assignment 3 - Jakarta Persistence (Model First), Integration Testing, and Automated Functional UI Testing
:source-highlighter: rouge
:max-width: 90%

== OBJECTIVE
Upon completion of this assignment, you will have demonstrated the ability to:

- Configure the Jakarta Persistence environment to use a database vendor of your choice
- Map a Java class to relational database table using Jakarta Persistence annotations
- Configure Jakarta Persistence generate database tables for mapped entities
- Perform CRUD operations on a Jakarta Persistence entity using the EntityManager interface
- Perform Integration Testing on a Jakarta Persistence repository using Arquillian
- Create Jakarta Faces web pages that access a Jakarta Persistence repository to perform CRUD operations on two related entities.
- Write a Functional UI Test for Jakarta Faces (JSF) using Selenium WebDriver.
- Build a web page that can export search results in EXCEL, PDF, or XML using the PrimeFaces DataExporter component

== PROBLEM DESCRIPTION
In assignment 1 you created a Jakarta Faces web application to manage a collection of data stored in a Firebase Realtime Database.
In this assignment you will create a Jakarta Faces web application to a manage a collection of data stored in a relational database on your machine. 

You can use one of the following relational database engine your assignment:

* Oracle 23ai database
* SQL Server 2022 database
* Postgres 16 database

You must use Jakarta Persistence to manage your relational database data.
The data you manage is the same as assignment 1 with additional fields for the *createTime*, *updateTime*, *version*,
and the *name* field replaced with a unique identifier field that is mapped to the primary key column of the database table.
You must use Bean Validation annotation to validate for at minimum required field validation.

You will write and run a Java program to generate the database schema for you entity.

You will write and run a Java program to populate your database with at least 10 rows of fake data.

You will create a Integration Test to verify that your Jakarta Persistence (JPA) repository methods to create data and to return all data are working as expected.

You will create a single Faces web page that allows the user to create data and to list all data.

You will use Selenium WebDriver to automated the web testing of your Faces page to create data and to list all data.

== GIT REPOSITORY SETUP
. Login to Moodle and navigate to the link to create a private github repository for this assignment.
. Click on *Accept this assignment* to allow github to create a private github repository for you.
. Wait for the *You are ready to go!* messaage then click on the link to navigate to your assignment repository
. Click on *Clone or download* button then copy the URL to your repository to the clipboard.
. You can now clone the git repository to the *~/IdeaProjects/dmit2015-1233-assignment03* folder from IntelliJ IDEA.

== PROJECT SETUP
. Open IntelliJ IDEA and create a new project using the *Jakarta EE* module and change following settings:
 .. Name: `dmit2015-assignment03-yourname`
 .. Location: `~/IdeaProjects/dmit2015-1233-assignment04`
 .. Template: `Web application`
 .. Application server: `<No appliation server>`  
 .. Group: `dmit2015`
 .. Artifact: `assignment03-yourname`
. Click *Next*
. Change the Version select menu to *Jakarta EE 10* and select the following specifications:
 .. Web Profile (10.0.0)
  Click *Create*

. Make the following changes to `pom.xml`
* Change the element value for both `maven.compiler.target` and `maven.compiler.source` to `*21*`.
* Change the element value for `junit.version` to `*5.10.2*`.

poml.xml
[source, xml]
----
<!-- MicroProfile Config is for reading configuration information from src/main/resources/META-INF/microprofile-config.properties file. -->
<dependency>
    <groupId>org.eclipse.microprofile.config</groupId>
    <artifactId>microprofile-config-api</artifactId>
    <version>3.1</version>
</dependency>

<!-- DataFaker is for creating fake data using a provider -->
<dependency>
    <groupId>net.datafaker</groupId>
    <artifactId>datafaker</artifactId>
    <version>2.2.2</version>
</dependency>

<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.32</version>
    <scope>provided</scope>
</dependency>

<dependency>
    <groupId>org.hibernate.orm</groupId>
    <artifactId>hibernate-core</artifactId>
    <version>6.5.2.Final</version>
</dependency>
<dependency>
    <groupId>org.hibernate.orm</groupId>
    <artifactId>hibernate-spatial</artifactId>
    <version>6.5.2.Final</version>
</dependency>

<dependency>
    <groupId>com.oracle.database.jdbc</groupId>
    <artifactId>ojdbc11</artifactId>
    <version>23.4.0.24.05</version>
</dependency>

<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>12.6.1.jre11</version>
</dependency>

<dependency>
    <groupId>org.postgresql</groupId>
    <artifactId>postgresql</artifactId>
    <version>42.7.3</version>
</dependency>

<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <version>2.2.224</version>
</dependency>

<dependency>
    <groupId>jakarta.faces</groupId>
    <artifactId>jakarta.faces-api</artifactId>
    <version>4.0.1</version>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>org.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>14.0.0</version>
    <classifier>jakarta</classifier>
</dependency>
<dependency>
    <groupId>com.googlecode.owasp-java-html-sanitizer</groupId>
    <artifactId>owasp-java-html-sanitizer</artifactId>
    <version>20240325.1</version>
</dependency>
<dependency>
    <groupId>org.webjars.npm</groupId>
    <artifactId>primeflex</artifactId>
    <version>3.3.1</version>
</dependency>
<dependency>
    <groupId>org.omnifaces</groupId>
    <artifactId>omnifaces</artifactId>
    <version>4.4.1</version>
</dependency>

<!-- Arquillian is for performing Integration Testing -->
<dependency>
    <groupId>org.eclipse</groupId>
    <artifactId>yasson</artifactId>
    <version>3.0.3</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.jboss.shrinkwrap.resolver</groupId>
    <artifactId>shrinkwrap-resolver-impl-maven</artifactId>
    <version>3.3.0</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.jboss.arquillian.junit5</groupId>
    <artifactId>arquillian-junit5-container</artifactId>
    <version>1.8.0.Final</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.jboss.arquillian.protocol</groupId>
    <artifactId>arquillian-protocol-servlet-jakarta</artifactId>
    <version>1.8.0.Final</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.wildfly.arquillian</groupId>
    <artifactId>wildfly-arquillian-container-managed</artifactId>
    <version>5.1.0.Beta2</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>2.0.13</version>
</dependency>
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>2.0.13</version>
</dependency>
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-core</artifactId>
    <version>2.23.1</version>
</dependency>

<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-params</artifactId>
    <version>${junit.version}</version>
    <scope>test</scope>
</dependency>

 <!-- AssertJ is for unit testing with Fluent Assertions -->
<dependency>
    <groupId>org.assertj</groupId>
    <artifactId>assertj-core</artifactId>
    <version>3.26.0</version>
    <scope>test</scope>
</dependency>


<!-- Dependency for Functional UI testing using Selenium WebDriver -->
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.21.0</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>5.8.0</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>selenium-jupiter</artifactId>
    <version>5.1.0</version>
    <scope>test</scope>
</dependency>

<!-- For PrimeFaces DataExporter PDF and Excel -->
<dependency>
    <groupId>com.github.librepdf</groupId>
    <artifactId>openpdf</artifactId>
    <version>2.0.2</version>
</dependency>
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi</artifactId>
    <version>5.2.5</version>
</dependency>
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml</artifactId>
    <version>5.2.5</version>
</dependency>

----

* Add the following dependencies to the `<plugins>` element.

poml.xml
[source, xml]
----
<!-- Plugin to build a bootable JAR for WildFly -->
<plugin>
    <!-- https://docs.wildfly.org/bootablejar/#wildfly_jar_dev_mode -->
    <!-- mvn wildfly-jar:dev-watch -->
    <groupId>org.wildfly.plugins</groupId>
    <artifactId>wildfly-jar-maven-plugin</artifactId>
    <version>11.0.2.Final</version>
    <configuration>
        <feature-pack-location>wildfly@maven(org.jboss.universe:community-universe)#32.0.1.Final</feature-pack-location>
        <layers>
            <!-- https://docs.wildfly.org/32/Bootable_Guide.html#wildfly_layers -->
            <layer>cloud-server</layer> <!-- includes ee-security -->
            <layer>jpa</layer>
            <layer>jsf</layer>
            <layer>microprofile-config</layer>
        </layers>
        <excluded-layers>
            <layer>deployment-scanner</layer>
        </excluded-layers>
        <plugin-options>
            <jboss-fork-embedded>true</jboss-fork-embedded>
        </plugin-options>
        <!-- https://docs.wildfly.org/bootablejar/#wildfly_jar_enabling_debug -->
        <jvmArguments>
            <!-- https://www.jetbrains.com/help/idea/attaching-to-local-process.html#attach-to-local -->
            <!-- To attach a debugger to the running server from IntelliJ IDEA
                1. From the main menu, choose `Run | Attach to Process`
                2. IntelliJ IDEA will show the list of running local processes. Select the process with the `xxx-bootable.jar` name to attach to.
            -->
            <arg>-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n</arg>
        </jvmArguments>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>package</goal>
            </goals>
        </execution>
    </executions>
</plugin>

<!-- Plugin to run unit tests-->
<!-- mvn test -->
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>3.2.5</version>
</plugin>

<!-- Plugin to run functional tests -->
<!--  mvn failsafe:integration-test -->
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-failsafe-plugin</artifactId>
    <version>3.2.5</version>
</plugin>

----

[start=5]
. Create the following Java packages
.. `dmit2015.config` for Java configuraton classes such as `ApplicationConfig.java`
.. `dmit2015.entity` for Java classes that is mapped to a database
.. `dmit2015.persistence` for Java classes to manage entity classes
.. `dmit2015.tools` for helper programs
.. `dmit2015.faces` for Jakarta Faces backing bean classes

. In the Java package `dmit2015.config`, create a new *DMIT2015 Jakarta Persistence ApplicationConfig* file then configure the JTA data source definition 
to use the database engine (sqlserver, oracle, postgres) you want to use.

. Navigate to the `src/main/resources/META-INF` folder and delete the existing *persistence.xml* file. 
In the `src/main/resources/META-INF` create a new *DMIT2015 Jakarta Persistence JTA persistence.xml* file then configure the persistence unit for the database engine you want to use.

. In the `src/main/webapp/WEB-INF` folder, edit the *web.xml* file and add the following elements:

web.xml
[source, xml]
----
<context-param>
    <param-name>jakarta.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL</param-name>
    <param-value>true</param-value>
</context-param>

<welcome-file-list>
    <welcome-file>index.xhtml</welcome-file>
</welcome-file-list>
----

[start=9]
. In the `src/main/webapp/WEB-INF` folder, create a new directory named *faces-templates*.
. In the `src/main/webapp/WEB-INF/faces-templates` folder, create a file using the *DMIT2015 Faces Template* file template.
. Edit the README.md file on your github repository with a test plan with columns for *Test Case*, *Test Data*, and *Expected Behaviour*. 

== REQUIREMENTS
. Implement a JPA entity class for your assignment 1 data and add additional fields for id, createTime, updateTime, and version.
The `createTime` is assigned by the system (database or your application) before persisting a entity.
The `updateTime` is assigned by the system (database or your application) before updating a entity.
The `version` is updated by the database when an entity is updated.

. Write and run a Java program to generate the database schema for your entity.

. Write and run a Java program to populate the database table with at least 10 rows of fake data.

. Create a new Jakarta Persistence respository with methods to perform CRUD (Create, Read One, Read All, Update, Delete) operations on the entity. 

. Create a new Arquillian Integration Test to test the methods of your JPA respository. 

. Run your Integration Test and verify that all of your methods in your JPA repository are working as expected.

. Create and code the Jakarta Faces (JSF) web pages and its supporting Java classes to peform CRUD operations on your JPA entity.

. Modify `src/main/webapp/WEB-INF/faces-templates/layout.xhtml` and add links to the web pages to *List YourEntity*, and *Create YourEntity*.

. Create a JUnit Test Case class to test the functionality of each web pages using Selenium WebDriver.
You can use the same test data that you used in your Jakarta Persistence Integration Test. 

. OPTIONAL CHALLENGE: In your entity list page use the http://www.primefaces.org:8080/showcase/ui/data/dataexporter/basic.xhtml?jfwid=00ae4[PrimeFaces DataExporter] component to add the option to export the data in the datatable to CSV, XLSX, or PDF file format.


== CODING REQUIREMENTS
* Java packages and classes must follow https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html[Java Naming Conventions] (*20%* deduction if you do not follow this requirement)
* All Java source files must include javadoc comments before the class with a description of the class, `@author` with your full name, and `@version` with the last date modifed. (*10%* deduction if you do not follow this requirement)
* Test case data is not documented (*10%* deduction if you do not follow this requirement)

== MARKING GUIDE

[cols="4,1"]
|===
|Requirement|Mark

| Demonstrate Database Schema Generation Works

| 1

| Demonstrate Database Data Generation Works

| 1

| Demonstrate Integration Test for your JPA repository class to create data and get all data. 

| 2

| Demonstrate single Jakarta Faces page to create data and to list all data. 

| 2

| Demonstrate automated web application testing to create to create data and to list all data. 

| 2

|===


== SUBMISSION REQUIREMENTS
* Commit and push your project to your git repository before the due date.
* Demonstrate in person during schedule class time the demonstration requirements on or before the first class after the due date.

