= DMIT2015 Assignment 5 - Jakarta Security with Content-Owner Only Access Data
:source-highlighter: rouge
:max-width: 90%

== OBJECTIVE
Upon completion of this assignment, you will have demonstrated the ability to:

* Secure a Jakarta EE appplication using Jakarta Security and/or Apache Shiro
* Apply container-managed authentication, authorization, and data protection.
* Secure the methods of a CDI managed bean using interceptors.
* Create and use custom error pages for common HTTP error codes.
* Implement content-owner only access data.

== PROBLEM DESCRIPTION
In this assignment you are going to convert the starter project for this assignment 
that contains a non-secure single-user Bill and Bill Payment application
to a secure multi-user application where each user can manage their own Bill and Bill Payment. 

The application will support two security groups: *Finance* and *Accounting*.
The *Finance* role is allowed to create, edit/update, and view their own Bill and BillPayment.
The *Accounting* role is allowed view Bill and BillPayment for all users and can delete Bill and BillPayment.

This assignment can be completed using either Jakarta Security OR Apache Shiro.

== GIT REPOSITORY SETUP
. Login to Moodle and navigate to the link to create a private github repository for this assignment.
. Click on *Accept this assignment* to allow github to create a private github repository for you.
. Wait for the *You are ready to go!* messaage then click on the link to navigate to your assignment repository
. Click on *Clone or download* button then copy the URL to your repository to the clipboard.

== PROJECT SETUP
. From IntelliJ IDEA open the project *dmit2015-assignment05-start* that is included in the GitHub repository for this assignment.
. Open a Terminal window and type the command `mvn wildfly-jar:dev-watch` to start the Jboss WildFly server.
. Once the project has been deployed open a browser and navigate to `http://localhost:8080` and using the navigation menu verify that the pages for List Bill and Create Bill are fully functional.
. Navigate to the `src/main/java/dmit2015/config` folder and open `ApplicationConfig.java` and change the `@DataSourceDefinition` 
to one of the following database: Oracle 23ai, SQL Server 2022, H2 file, PostgreSQL, MySQL, or MariaDB.
. Open a browser and verify that the pages for List Bill and Create Bill are still fully functional.


== REQUIREMENTS
. Configure the *wildfly-jar-maven-plugin* in `pom.xml` to:
.. Add a `layer` element for `ee-security`
.. Add a `layer` element for `undertow-https`
.. Add a `cli-sessions` element to run CLI script file to enable EE security

. Configure web application to transport all URLs over HTTPS.

. Configure web application to restrict access to the following url patterns and role name.
+
[cols="2,1"]
|===
| url-pattern | role-name

| /bills/create.xhtml

/bills/edit.xhtml
| Finance
|===
+
.  Configure web application to restrict access to the following url patterns and role name.
+
[cols="2,1"]
|===
| url-pattern | role-name

| /bills/delete.xhtml

/bills/payments/create.xhtml

/bills/payments/edit.xhtml

/bills/payments/delete.xhtml
| Accounting
|===
+
.  Configure web application to restrict access to the following url patterns and role names.
+
[cols="2,1"]
|===
| url-pattern | role-name

| /bills/index.xhtml

/bills/details.xhtml

/bills/detailsContent.xhtml

/bills/payments/index.xhtml

/bills/payments/details.xhtml

/bills/payments/detailsContent.xhtml
| Accounting

Finance

|===
+

. Configure application to use either LDAP or Database authentication. 
For LDAP authentication configure you application to use the Windows Server 2022 VM as the LDAP server. 
For Database authentication you will need to create the same user accounts from the Windows Server 2022 VM.

. Modify the Faces layout file `/src/main/webapp/WEB-INF/faces-templates/layout.xhml` with a link to login and a link logout.

. Modify `Bill.java` and add a property for the authenticated `username`.

. Using either an CDI Interceptor or modify the `BillRepository.java` method `create()` 
directly to set the `username` of the Bill before it is persisted.

. Modify `BillRepository.java` method `findAll()` directly to work as follows:
.. If the caller is anonymous (non-authenticated) user then throw an `RuntimeException`.
.. If the caller is the role *Finance* then return a list of Bill entity filter by the username of the caller.
.. If the caller is the role *Accounting* then return a list of a Bill entity.
.. If the caller is not in the role *Finance* or *Accounting* then return a empty list.

. Modify `BillPayment.java` and add a property for the authenticated `username`.

. Using either an CDI Interceptor or modify the `BillPaymentRepository.java` method `create()` 
directly to set the `username` of the BillPayment before it is persisted.

. Modify `BillPaymentRepository.java` method `findAll()` to work as follows:
.. If the caller is anonymous (non-authenticated) user then throw an `RuntimeException`.
.. If the caller is the role *Finance* then return a list of BillPayment entity filter by the username of the caller.
.. If the caller is the role *Accounting* then return all BillPayment entity.
.. If the caller is not in the role *Finance* or *Accounting* then return a empty list.

. Configure your application to restrict access to the `create` and `update` methods to the role *Finance* in `BillRepository.java`.

. Configure your application to restrict access to the `create` and `update` methods to the role *Accounting* in `BillPaymentRepository.java`.

. Configure your application to restrict access to the `remove` and `delete` methods to the role *Accounting* in `BillRepository.java` and `BillPaymentRepository.java`.

. Configure your application to restrict access to the `findOneById` method to the roles *Finance* and *Accounting*.
   
. Configure your project to display custom error pages for error codes 403, 404, and 500.

. Test your application that you can login using an *Finance* account and create/edit Bills and BillPayments. 

. To avoid losing all your data each time your application starts.
.. Open *ApplicationConfig.java* comment out the line `url="jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;",`
and uncomment the line `url="jdbc:h2:file:~/jdk/databases/h2/DMIT2015CourseDB;",` 
.. Open *persistence.xml* change the property `jakarta.persistence.schema-generation.database.action` value 
from `drop-and-create` to `create`.


== MARKING GUIDE

[cols="4,1"]
|===
| Demonstration Requirement | Marks

| Demonstrate that all Web application URLs are transported over HTTPS
| 1

| Demonstrate that you can login using an *Finance* account, create a bill, view your own bills, 
and a custom 403 error page is shown when you try to delete a bill or pay a bill.
| 2

| Demonstrate that you can login using an *Accounting* account, view all bills and payments, pay a bill, delete a bill, 
delete a payment, and a custom 403 error page is shown when you try to create or edit a bill.
| 2

| Demonstrate method-level security by login using an *Sales* account, 
using the Public menu links to create a new bill results in an access denied message and the list page shows no bills.
| 2

|===


== SUBMISSION/DEMONSTRATION REQUIREMENTS
* Commit and push your project to your git repository before the due date.
* Demonstrate in person the demonstration requirements on or before the due date.

== Resources
* https://eclipse-ee4j.github.io/jakartaee-tutorial/#security-2[Security in the Jakarta EE Platform]
* https://javaee.github.io/tutorial/interceptors.html#GKEED[Using Jakarta EE Interceptors]
* https://jakarta.ee/specifications/interceptors/2.0/interceptors-spec-2.0.html[Jakarta Interceptors]
* https://shiro.apache.org/jakarta-ee.html[Apache Shiro Jakarta EE Integration]
* https://shiro.apache.org/web.html[Apache Shiro Web Support]
* https://shiro.apache.org/documentation.html[Apache Shiro Documentation]